[workspace]
members = ["src-tauri", "core"]
resolver = "2"

[workspace.dependencies]
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"

uuid = "1.28.0"
chrono = "0.4.45"

zelefy_common = { path = "../../packages/shared-rs/common" }

[profile.release]
strip = true
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
